import type { WorkingQuery } from './working-query';

/**
 * A named working query kept in this browser.
 *
 * The shape is locked by the project overview: feature 16 moves it to Supabase
 * as a copy, not a redesign, so nothing here may drift from those four fields.
 */
export interface SavedQuery {
  name: string;
  query: WorkingQuery;
  /**
   * The `meta.vintages` ids observed when this was saved, which is what makes
   * reproduction exact. Empty when no result for this query had been seen.
   */
  vintageIds: number[];
  /** ISO-8601, generated by this app, so it carries a `Z`. */
  savedAt: string;
}

/**
 * `3 ind × 2 ctry · 2018–2030`, matching the design's abbreviations.
 *
 * Deliberately terse and unpluralised: the column is a glance, not prose, and
 * the design shows `1 ind × 4 ctry` rather than `1 indicator`.
 */
export function scopeLabel(query: WorkingQuery): string {
  const countries =
    query.countries.length === 0 ? 'all ctry' : `${query.countries.length} ctry`;

  return `${query.indicators.length} ind × ${countries} · ${yearLabel(query)}`;
}

/** The year range as the scope column shows it. */
function yearLabel(query: WorkingQuery): string {
  const { yearFrom, yearTo } = query;

  if (yearFrom === null && yearTo === null) {
    return 'all years';
  }
  if (yearFrom === null) {
    return `to ${yearTo}`;
  }
  if (yearTo === null) {
    return `from ${yearFrom}`;
  }

  return `${yearFrom}–${yearTo}`;
}

/**
 * `latest`, `pinned id 12`, or the label when the query pinned one by name.
 *
 * `VintageSelector` is `'latest' | number | string`, and a string that is not
 * `latest` is a vintage label, so it is shown as written.
 */
export function vintageLabel(query: WorkingQuery): string {
  const { vintage } = query;

  if (vintage === 'latest') {
    return 'latest';
  }

  return typeof vintage === 'number' ? `pinned id ${vintage}` : vintage;
}

/** The `YYYY-MM-DD` prefix. `savedAt` is ours, so it is always well formed. */
export function savedDate(saved: SavedQuery): string {
  return saved.savedAt.slice(0, 10);
}

/**
 * The vintage id Reproduce would pin, or null when it cannot be offered.
 *
 * `WorkingQuery.vintage` holds one selector and, per the consumer guide,
 * pinning a vintage implies its source. A result that drew on two vintages
 * therefore cannot be re-asked as a single pinned query: pinning the WEO id
 * would drop the WDI rows and return a subset while claiming to reproduce. Null
 * for zero ids too, since there is nothing recorded to pin.
 */
export function reproduceTarget(saved: SavedQuery): number | null {
  return saved.vintageIds.length === 1 ? saved.vintageIds[0] : null;
}

/** Why Reproduce is unavailable, for the disabled control's explanation. */
export function reproduceBlockedReason(saved: SavedQuery): string | null {
  if (saved.vintageIds.length === 1) {
    return null;
  }

  return saved.vintageIds.length === 0
    ? 'No vintage ids were recorded for this save, so there is nothing to pin.'
    : 'This result drew on more than one vintage; pinning one would drop the other.';
}
